general.import = [ 
    "~/.config/alacritty/font.toml",
    "~/.config/alacritty/colorschemes/gruvbox.toml"
]

colors.draw_bold_text_with_bright_colors = true
general.live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 1
dynamic_padding = true

[scrolling]
history = 10_000

[bell]
animation = "EaseOutExpo"
duration = 0

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"

[cursor]
unfocused_hollow = true

  [cursor.style]
  shape = "Underline"
  blinking = "On"
