[font]
size = 12

[font.normal]
family = "JetBrainsMono NF"
style = "Medium"

[font.bold]
family = "JetBrainsMono NF"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono NF"
style = "Medium Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "SemiBold Italic"
