#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Lock\n⏾ Sleep" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"  Power Off") poweroff ;;
	"  Restart") reboot ;;
	"  Lock") betterlockscreen -l ;;
	"⏾ Sleep") betterlockscreen -s ;;
	*) exit 1 ;;
esac
